//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace SUrl.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SUrlContext : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SUrlContext object using the connection string found in the 'SUrlContext' section of the application configuration file.
        /// </summary>
        public SUrlContext() : base("name=SUrlContext", "SUrlContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SUrlContext object.
        /// </summary>
        public SUrlContext(string connectionString) : base(connectionString, "SUrlContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SUrlContext object.
        /// </summary>
        public SUrlContext(EntityConnection connection) : base(connection, "SUrlContext")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<tblSUrl> tblSUrls
        {
            get
            {
                if ((_tblSUrls == null))
                {
                    _tblSUrls = base.CreateObjectSet<tblSUrl>("tblSUrls");
                }
                return _tblSUrls;
            }
        }
        private ObjectSet<tblSUrl> _tblSUrls;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the tblSUrls EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotblSUrls(tblSUrl tblSUrl)
        {
            base.AddObject("tblSUrls", tblSUrl);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SUrlModel", Name="tblSUrl")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class tblSUrl : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new tblSUrl object.
        /// </summary>
        /// <param name="sUrl_ID">Initial value of the SUrl_ID property.</param>
        /// <param name="longUrl">Initial value of the LongUrl property.</param>
        /// <param name="shortUrl">Initial value of the ShortUrl property.</param>
        public static tblSUrl CreatetblSUrl(global::System.Int32 sUrl_ID, global::System.String longUrl, global::System.String shortUrl)
        {
            tblSUrl tblSUrl = new tblSUrl();
            tblSUrl.SUrl_ID = sUrl_ID;
            tblSUrl.LongUrl = longUrl;
            tblSUrl.ShortUrl = shortUrl;
            return tblSUrl;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 SUrl_ID
        {
            get
            {
                return _SUrl_ID;
            }
            set
            {
                if (_SUrl_ID != value)
                {
                    OnSUrl_IDChanging(value);
                    ReportPropertyChanging("SUrl_ID");
                    _SUrl_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("SUrl_ID");
                    OnSUrl_IDChanged();
                }
            }
        }
        private global::System.Int32 _SUrl_ID;
        partial void OnSUrl_IDChanging(global::System.Int32 value);
        partial void OnSUrl_IDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String LongUrl
        {
            get
            {
                return _LongUrl;
            }
            set
            {
                OnLongUrlChanging(value);
                ReportPropertyChanging("LongUrl");
                _LongUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("LongUrl");
                OnLongUrlChanged();
            }
        }
        private global::System.String _LongUrl;
        partial void OnLongUrlChanging(global::System.String value);
        partial void OnLongUrlChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String ShortUrl
        {
            get
            {
                return _ShortUrl;
            }
            set
            {
                OnShortUrlChanging(value);
                ReportPropertyChanging("ShortUrl");
                _ShortUrl = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("ShortUrl");
                OnShortUrlChanged();
            }
        }
        private global::System.String _ShortUrl;
        partial void OnShortUrlChanging(global::System.String value);
        partial void OnShortUrlChanged();

        #endregion

    
    }

    #endregion

    
}
